<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompletePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds to add complete permissions from laptop database.
     */
    public function run(): void
    {
        $this->command->info('📝 Adding complete permissions from laptop database...');

        // Complete permissions data from laptop database (aypsis_yang_benar.sql)
        $permissions = [
            // Core permissions (ID 1-34)
            ['id' => 1, 'name' => 'master-karyawan', 'description' => 'Akses Master Karyawan'],
            ['id' => 2, 'name' => 'master-user', 'description' => 'Akses Master User'],
            ['id' => 3, 'name' => 'master-kontainer', 'description' => 'Akses Master Kontainer'],
            ['id' => 4, 'name' => 'master-permohonan', 'description' => 'Akses Master Permohonan'],
            ['id' => 5, 'name' => 'permohonan-create', 'description' => 'Membuat Permohonan'],
            ['id' => 6, 'name' => 'permohonan-view', 'description' => 'Melihat Permohonan'],
            ['id' => 7, 'name' => 'permohonan-edit', 'description' => 'Mengedit Permohonan'],
            ['id' => 8, 'name' => 'permohonan-delete', 'description' => 'Menghapus Permohonan'],
            ['id' => 9, 'name' => 'master-tujuan', 'description' => 'Akses Master Tujuan'],
            ['id' => 10, 'name' => 'master-kegiatan', 'description' => 'Akses Master Kegiatan'],
            ['id' => 11, 'name' => 'master-permission', 'description' => 'Akses Master Izin'],
            ['id' => 12, 'name' => 'master-mobil', 'description' => 'Akses Master Mobil'],
            ['id' => 13, 'name' => 'master-pricelist-sewa-kontainer', 'description' => 'Akses Master Pricelist Sewa Kontainer'],
            ['id' => 14, 'name' => 'master-pranota-supir', 'description' => 'Akses Master Pranota Supir'],
            ['id' => 15, 'name' => 'master-pembayaran-pranota-supir', 'description' => 'Akses Pembayaran Pranota Supir'],
            ['id' => 16, 'name' => 'login', 'description' => 'Izin untuk route: login'],
            ['id' => 17, 'name' => 'logout', 'description' => 'Izin untuk route: logout'],
            ['id' => 18, 'name' => 'tagihan-kontainer-sewa.group.show', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/group/{vendor}/{tanggal}'],
            ['id' => 19, 'name' => 'tagihan-kontainer-sewa.adjust_price', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/adjust-price'],
            ['id' => 20, 'name' => 'tagihan-kontainer-sewa.search_by_kontainer', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/search-by-kontainer'],
            ['id' => 21, 'name' => 'tagihan-kontainer-sewa.group.adjust_price', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/group/{vendor}/{tanggal}'],
            ['id' => 22, 'name' => 'tagihan-kontainer-sewa.history', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/history'],
            ['id' => 23, 'name' => 'tagihan-kontainer-sewa.rollover', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/{id}/rollover'],
            ['id' => 24, 'name' => 'tagihan-kontainer-sewa.export', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/export'],
            ['id' => 25, 'name' => 'tagihan-kontainer-sewa.template', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/template'],
            ['id' => 26, 'name' => 'tagihan-kontainer-sewa.import', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/import'],
            ['id' => 27, 'name' => 'tagihan-kontainer-sewa.index', 'description' => 'Izin untuk route: tagihan-kontainer-sewa'],
            ['id' => 28, 'name' => 'tagihan-kontainer-sewa.create', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/create'],
            ['id' => 29, 'name' => 'tagihan-kontainer-sewa.store', 'description' => 'Izin untuk route: tagihan-kontainer-sewa'],
            ['id' => 30, 'name' => 'tagihan-kontainer-sewa.show', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/{tagihan_kontainer_sewa}'],
            ['id' => 31, 'name' => 'tagihan-kontainer-sewa.edit', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/{tagihan_kontainer_sewa}/edit'],
            ['id' => 32, 'name' => 'tagihan-kontainer-sewa.update', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/{tagihan_kontainer_sewa}'],
            ['id' => 33, 'name' => 'tagihan-kontainer-sewa.destroy', 'description' => 'Izin untuk route: tagihan-kontainer-sewa/{tagihan_kontainer_sewa}'],
            ['id' => 34, 'name' => 'dashboard', 'description' => 'Izin untuk route: dashboard'],

            // Continue with more permissions...
            ['id' => 35, 'name' => 'master.karyawan.print', 'description' => 'Izin untuk route: master/karyawan/print'],
            ['id' => 36, 'name' => 'master.karyawan.print.single', 'description' => 'Izin untuk route: master/karyawan/{karyawan}/print'],
            ['id' => 37, 'name' => 'master.karyawan.import', 'description' => 'Izin untuk route: master/karyawan/import'],
            ['id' => 38, 'name' => 'master.karyawan.import.store', 'description' => 'Izin untuk route: master/karyawan/import'],
            ['id' => 39, 'name' => 'master.karyawan.export', 'description' => 'Izin untuk route: master/karyawan/export'],
            ['id' => 40, 'name' => 'master.karyawan.index', 'description' => 'Izin untuk route: master/karyawan'],
            ['id' => 41, 'name' => 'master.karyawan.create', 'description' => 'Izin untuk route: master/karyawan/create'],
            ['id' => 42, 'name' => 'master.karyawan.store', 'description' => 'Izin untuk route: master/karyawan'],
            ['id' => 43, 'name' => 'master.karyawan.show', 'description' => 'Izin untuk route: master/karyawan/{karyawan}'],
            ['id' => 44, 'name' => 'master.karyawan.edit', 'description' => 'Izin untuk route: master/karyawan/{karyawan}/edit'],
            ['id' => 45, 'name' => 'master.karyawan.update', 'description' => 'Izin untuk route: master/karyawan/{karyawan}'],
            ['id' => 46, 'name' => 'master.karyawan.destroy', 'description' => 'Izin untuk route: master/karyawan/{karyawan}'],
            ['id' => 47, 'name' => 'master.user.index', 'description' => 'Izin untuk route: master/user'],
            ['id' => 48, 'name' => 'master.user.create', 'description' => 'Izin untuk route: master/user/create'],
            ['id' => 49, 'name' => 'master.user.store', 'description' => 'Izin untuk route: master/user'],
            ['id' => 50, 'name' => 'master.user.show', 'description' => 'Izin untuk route: master/user/{user}'],
            ['id' => 51, 'name' => 'master.user.edit', 'description' => 'Izin untuk route: master/user/{user}/edit'],
            ['id' => 52, 'name' => 'master.user.update', 'description' => 'Izin untuk route: master/user/{user}'],
            ['id' => 53, 'name' => 'master.user.destroy', 'description' => 'Izin untuk route: master/user/{user}'],
            ['id' => 54, 'name' => 'master.kontainer.index', 'description' => 'Izin untuk route: master/kontainer'],
            ['id' => 55, 'name' => 'master.kontainer.create', 'description' => 'Izin untuk route: master/kontainer/create'],
            ['id' => 56, 'name' => 'master.kontainer.store', 'description' => 'Izin untuk route: master/kontainer'],
            ['id' => 57, 'name' => 'master.kontainer.show', 'description' => 'Izin untuk route: master/kontainer/{kontainer}'],
            ['id' => 58, 'name' => 'master.kontainer.edit', 'description' => 'Izin untuk route: master/kontainer/{kontainer}/edit'],
            ['id' => 59, 'name' => 'master.kontainer.update', 'description' => 'Izin untuk route: master/kontainer/{kontainer}'],
            ['id' => 60, 'name' => 'master.kontainer.destroy', 'description' => 'Izin untuk route: master/kontainer/{kontainer}'],
            ['id' => 61, 'name' => 'master.tujuan.index', 'description' => 'Izin untuk route: master/tujuan'],
            ['id' => 62, 'name' => 'master.tujuan.create', 'description' => 'Izin untuk route: master/tujuan/create'],
            ['id' => 63, 'name' => 'master.tujuan.store', 'description' => 'Izin untuk route: master/tujuan'],
            ['id' => 64, 'name' => 'master.tujuan.show', 'description' => 'Izin untuk route: master/tujuan/{tujuan}'],
            ['id' => 65, 'name' => 'master.tujuan.edit', 'description' => 'Izin untuk route: master/tujuan/{tujuan}/edit'],
            ['id' => 66, 'name' => 'master.tujuan.update', 'description' => 'Izin untuk route: master/tujuan/{tujuan}'],
            ['id' => 67, 'name' => 'master.tujuan.destroy', 'description' => 'Izin untuk route: master/tujuan/{tujuan}'],
            ['id' => 68, 'name' => 'master.kegiatan.index', 'description' => 'Izin untuk route: master/kegiatan'],
            ['id' => 69, 'name' => 'master.kegiatan.create', 'description' => 'Izin untuk route: master/kegiatan/create'],
            ['id' => 70, 'name' => 'master.kegiatan.store', 'description' => 'Izin untuk route: master/kegiatan'],
            ['id' => 71, 'name' => 'master.kegiatan.show', 'description' => 'Izin untuk route: master/kegiatan/{kegiatan}'],
            ['id' => 72, 'name' => 'master.kegiatan.edit', 'description' => 'Izin untuk route: master/kegiatan/{kegiatan}/edit'],
            ['id' => 73, 'name' => 'master.kegiatan.update', 'description' => 'Izin untuk route: master/kegiatan/{kegiatan}'],
            ['id' => 74, 'name' => 'master.kegiatan.destroy', 'description' => 'Izin untuk route: master/kegiatan/{kegiatan}'],
            ['id' => 75, 'name' => 'master.kegiatan.template', 'description' => 'Izin untuk route: master/kegiatan/template/csv'],
            ['id' => 76, 'name' => 'master.kegiatan.import', 'description' => 'Izin untuk route: master/kegiatan/import/csv'],
            ['id' => 77, 'name' => 'master.permission.index', 'description' => 'Izin untuk route: master/permission'],
            ['id' => 78, 'name' => 'master.permission.create', 'description' => 'Izin untuk route: master/permission/create'],
            ['id' => 79, 'name' => 'master.permission.store', 'description' => 'Izin untuk route: master/permission'],
            ['id' => 80, 'name' => 'master.permission.show', 'description' => 'Izin untuk route: master/permission/{permission}'],
            ['id' => 81, 'name' => 'master.permission.edit', 'description' => 'Izin untuk route: master/permission/{permission}/edit'],
            ['id' => 82, 'name' => 'master.permission.update', 'description' => 'Izin untuk route: master/permission/{permission}'],
            ['id' => 83, 'name' => 'master.permission.destroy', 'description' => 'Izin untuk route: master/permission/{permission}'],
            ['id' => 84, 'name' => 'master.mobil.index', 'description' => 'Izin untuk route: master/mobil'],
            ['id' => 85, 'name' => 'master.mobil.create', 'description' => 'Izin untuk route: master/mobil/create'],
            ['id' => 86, 'name' => 'master.mobil.store', 'description' => 'Izin untuk route: master/mobil'],
            ['id' => 87, 'name' => 'master.mobil.show', 'description' => 'Izin untuk route: master/mobil/{mobil}'],
            ['id' => 88, 'name' => 'master.mobil.edit', 'description' => 'Izin untuk route: master/mobil/{mobil}/edit'],
            ['id' => 89, 'name' => 'master.mobil.update', 'description' => 'Izin untuk route: master/mobil/{mobil}'],
            ['id' => 90, 'name' => 'master.mobil.destroy', 'description' => 'Izin untuk route: master/mobil/{mobil}'],
            ['id' => 91, 'name' => 'master.pricelist-sewa-kontainer.index', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer'],
            ['id' => 92, 'name' => 'master.pricelist-sewa-kontainer.create', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer/create'],
            ['id' => 93, 'name' => 'master.pricelist-sewa-kontainer.store', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer'],
            ['id' => 94, 'name' => 'master.pricelist-sewa-kontainer.show', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer/{pricelist_sewa_kontainer}'],
            ['id' => 95, 'name' => 'master.pricelist-sewa-kontainer.edit', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer/{pricelist_sewa_kontainer}/edit'],
            ['id' => 96, 'name' => 'master.pricelist-sewa-kontainer.update', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer/{pricelist_sewa_kontainer}'],
            ['id' => 97, 'name' => 'master.pricelist-sewa-kontainer.destroy', 'description' => 'Izin untuk route: master/pricelist-sewa-kontainer/{pricelist_sewa_kontainer}'],
            ['id' => 98, 'name' => 'permohonan.export', 'description' => 'Izin untuk route: permohonan/export'],
            ['id' => 99, 'name' => 'permohonan.import', 'description' => 'Izin untuk route: permohonan/import'],
            ['id' => 100, 'name' => 'permohonan.index', 'description' => 'Izin untuk route: permohonan'],
            ['id' => 101, 'name' => 'permohonan.create', 'description' => 'Izin untuk route: permohonan/create'],
            ['id' => 102, 'name' => 'permohonan.store', 'description' => 'Izin untuk route: permohonan'],
            ['id' => 103, 'name' => 'permohonan.show', 'description' => 'Izin untuk route: permohonan/{permohonan}'],
            ['id' => 104, 'name' => 'permohonan.edit', 'description' => 'Izin untuk route: permohonan/{permohonan}/edit'],
            ['id' => 105, 'name' => 'permohonan.update', 'description' => 'Izin untuk route: permohonan/{permohonan}'],
            ['id' => 106, 'name' => 'permohonan.destroy', 'description' => 'Izin untuk route: permohonan/{permohonan}'],
            ['id' => 107, 'name' => 'pranota-supir.index', 'description' => 'Izin untuk route: pranota-supir'],
            ['id' => 108, 'name' => 'pranota-supir.create', 'description' => 'Izin untuk route: pranota-supir/create'],
            ['id' => 109, 'name' => 'pranota-supir.print', 'description' => 'Izin untuk route: pranota-supir/{pranotaSupir}/print'],
            ['id' => 110, 'name' => 'pranota-supir.show', 'description' => 'Izin untuk route: pranota-supir/{pranotaSupir}'],
            ['id' => 111, 'name' => 'pranota-supir.store', 'description' => 'Izin untuk route: pranota-supir'],
            ['id' => 112, 'name' => 'pranota-tagihan-kontainer.store', 'description' => 'Izin untuk route: pranota-tagihan-kontainer'],
            ['id' => 113, 'name' => 'pranota-tagihan-kontainer.destroy', 'description' => 'Izin untuk route: pranota-tagihan-kontainer/{id}'],
            ['id' => 114, 'name' => 'pembayaran-pranota-tagihan-kontainer.index', 'description' => 'Izin untuk route: pembayaran-pranota-tagihan-kontainer'],
            ['id' => 115, 'name' => 'pembayaran-pranota-tagihan-kontainer.export', 'description' => 'Izin untuk route: pembayaran-pranota-tagihan-kontainer/export'],
            ['id' => 116, 'name' => 'pembayaran-pranota-tagihan-kontainer.import', 'description' => 'Izin untuk route: pembayaran-pranota-tagihan-kontainer/import'],
            ['id' => 117, 'name' => 'pembayaran-pranota-tagihan-kontainer.create', 'description' => 'Izin untuk route: pembayaran-pranota-tagihan-kontainer/buat'],
            ['id' => 118, 'name' => 'pembayaran-pranota-tagihan-kontainer.store', 'description' => 'Izin untuk route: pembayaran-pranota-tagihan-kontainer/simpan'],
            ['id' => 119, 'name' => 'pembayaran-pranota-tagihan-kontainer.history', 'description' => 'Izin untuk route: pembayaran-pranota-tagihan-kontainer/riwayat'],
            ['id' => 120, 'name' => 'pembayaran-pranota-supir.index', 'description' => 'Izin untuk route: pembayaran-pranota-supir'],
            ['id' => 121, 'name' => 'pembayaran-pranota-supir.print', 'description' => 'Izin untuk route: pembayaran-pranota-supir/{pembayaran}/print'],
            ['id' => 122, 'name' => 'pembayaran-pranota-supir.create', 'description' => 'Izin untuk route: pembayaran-pranota-supir/buat'],
            ['id' => 123, 'name' => 'pembayaran-pranota-supir.store', 'description' => 'Izin untuk route: pembayaran-pranota-supir/simpan'],
            ['id' => 124, 'name' => 'supir.dashboard', 'description' => 'Izin untuk route: supir/dashboard'],
            ['id' => 125, 'name' => 'supir.checkpoint.create', 'description' => 'Izin untuk route: supir/permohonan/{permohonan}/checkpoint'],
            ['id' => 126, 'name' => 'supir.checkpoint.store', 'description' => 'Izin untuk route: supir/permohonan/{permohonan}/checkpoint'],
            ['id' => 127, 'name' => 'approval.dashboard', 'description' => 'Izin untuk route: approval'],
            ['id' => 128, 'name' => 'approval.mass_process', 'description' => 'Izin untuk route: approval/mass-process'],
            ['id' => 129, 'name' => 'approval.create', 'description' => 'Izin untuk route: approval/{permohonan}'],
            ['id' => 130, 'name' => 'approval.store', 'description' => 'Izin untuk route: approval/{permohonan}'],
            ['id' => 131, 'name' => 'admin.features', 'description' => 'Izin untuk route: admin/features'],
            ['id' => 132, 'name' => 'storage.local', 'description' => 'Izin untuk route: storage/{path}'],
            ['id' => 133, 'name' => 'master-pranota-tagihan-kontainer', 'description' => 'Akses Master Pranota Tagihan Kontainer'],
            ['id' => 134, 'name' => 'admin.debug.perms', 'description' => 'Izin untuk route: admin.debug.perms'],
            ['id' => 135, 'name' => 'master-pranota', 'description' => null],
            ['id' => 150, 'name' => 'approval.riwayat', 'description' => 'Approval Riwayat'],
            ['id' => 179, 'name' => 'admin.user-approval.index', 'description' => 'Admin User Approval Index'],
            ['id' => 180, 'name' => 'admin.user-approval.show', 'description' => 'Admin User Approval Show'],
            ['id' => 181, 'name' => 'admin.user-approval.approve', 'description' => 'Admin User Approval Approve'],
            ['id' => 182, 'name' => 'admin.user-approval.reject', 'description' => 'Admin User Approval Reject'],
            ['id' => 183, 'name' => 'profile.show', 'description' => 'Profile Show'],
            ['id' => 184, 'name' => 'profile.edit', 'description' => 'Profile Edit'],
            ['id' => 185, 'name' => 'profile.update.account', 'description' => 'Profile Update Account'],
            ['id' => 186, 'name' => 'profile.update.personal', 'description' => 'Profile Update Personal'],
            ['id' => 187, 'name' => 'profile.update.avatar', 'description' => 'Profile Update Avatar'],
            ['id' => 188, 'name' => 'profile.destroy', 'description' => 'Profile Destroy'],
            ['id' => 189, 'name' => 'tagihan-kontainer', 'description' => 'Akses menu Tagihan Kontainer Sewa'],
            ['id' => 190, 'name' => 'pranota-supir', 'description' => 'Akses menu Pranota Supir'],
            ['id' => 191, 'name' => 'pembayaran-pranota-supir', 'description' => 'Akses menu Pembayaran Pranota Supir'],
            ['id' => 192, 'name' => 'permohonan', 'description' => 'Akses menu permohonan memo'],
            ['id' => 193, 'name' => 'user-approval', 'description' => 'Persetujuan user baru'],
            ['id' => 265, 'name' => 'tagihan-kontainer-view', 'description' => 'View tagihan kontainer'],
            ['id' => 266, 'name' => 'tagihan-kontainer-create', 'description' => 'Create tagihan kontainer'],
            ['id' => 267, 'name' => 'tagihan-kontainer-update', 'description' => 'Update tagihan kontainer'],
            ['id' => 268, 'name' => 'tagihan-kontainer-delete', 'description' => 'Delete tagihan kontainer'],
            ['id' => 269, 'name' => 'tagihan-kontainer-approve', 'description' => 'Approve tagihan kontainer'],
            ['id' => 270, 'name' => 'tagihan-kontainer-print', 'description' => 'Print tagihan kontainer'],
            ['id' => 271, 'name' => 'tagihan-kontainer-export', 'description' => 'Export tagihan kontainer'],
            ['id' => 272, 'name' => 'pranota-supir-view', 'description' => 'View pranota supir'],
            ['id' => 273, 'name' => 'pranota-supir-create', 'description' => 'Create pranota supir'],
            ['id' => 274, 'name' => 'pranota-supir-update', 'description' => 'Update pranota supir'],
            ['id' => 275, 'name' => 'pranota-supir-delete', 'description' => 'Delete pranota supir'],
            ['id' => 276, 'name' => 'pranota-supir-approve', 'description' => 'Approve pranota supir'],
            ['id' => 277, 'name' => 'pranota-supir-print', 'description' => 'Print pranota supir'],
            ['id' => 278, 'name' => 'pranota-supir-export', 'description' => 'Export pranota supir'],
            ['id' => 297, 'name' => 'pembayaran-pranota-supir.view', 'description' => 'Akses Pembayaran pranota supir view'],
            ['id' => 298, 'name' => 'pembayaran-pranota-supir.update', 'description' => 'Akses Pembayaran pranota supir update'],
            ['id' => 299, 'name' => 'pembayaran-pranota-supir.delete', 'description' => 'Akses Pembayaran pranota supir delete'],
            ['id' => 300, 'name' => 'pembayaran-pranota-supir.approve', 'description' => 'Akses Pembayaran pranota supir approve'],
            ['id' => 301, 'name' => 'pembayaran-pranota-supir.export', 'description' => 'Akses Pembayaran pranota supir export'],
            ['id' => 302, 'name' => 'permohonan.approve', 'description' => 'Akses Permohonan approve'],
            ['id' => 303, 'name' => 'permohonan.print', 'description' => 'Akses Permohonan print'],
            ['id' => 304, 'name' => 'pembayaran-pranota-supir-view', 'description' => 'Akses Pembayaran pranota supir view'],
            ['id' => 305, 'name' => 'pembayaran-pranota-supir-create', 'description' => 'Akses Pembayaran pranota supir create'],
            ['id' => 306, 'name' => 'pembayaran-pranota-supir-update', 'description' => 'Akses Pembayaran pranota supir update'],
            ['id' => 307, 'name' => 'pembayaran-pranota-supir-delete', 'description' => 'Akses Pembayaran pranota supir delete'],
            ['id' => 308, 'name' => 'pembayaran-pranota-supir-approve', 'description' => 'Akses Pembayaran pranota supir approve'],
            ['id' => 309, 'name' => 'pembayaran-pranota-supir-print', 'description' => 'Akses Pembayaran pranota supir print'],
            ['id' => 310, 'name' => 'pembayaran-pranota-supir-export', 'description' => 'Akses Pembayaran pranota supir export'],
            ['id' => 311, 'name' => 'permohonan-update', 'description' => 'Akses Permohonan update'],
            ['id' => 312, 'name' => 'permohonan-approve', 'description' => 'Akses Permohonan approve'],
            ['id' => 313, 'name' => 'permohonan-print', 'description' => 'Akses Permohonan print'],
            ['id' => 314, 'name' => 'permohonan-export', 'description' => 'Akses Permohonan export'],
            ['id' => 315, 'name' => 'master-karyawan.view', 'description' => 'Master karyawan view'],
            ['id' => 316, 'name' => 'master-karyawan.create', 'description' => 'Master karyawan create'],
            ['id' => 317, 'name' => 'master-karyawan.update', 'description' => 'Master karyawan update'],
            ['id' => 318, 'name' => 'master-karyawan.delete', 'description' => 'Master karyawan delete'],
            ['id' => 319, 'name' => 'master-user.view', 'description' => 'Master user view'],
            ['id' => 320, 'name' => 'master-user.create', 'description' => 'Master user create'],
            ['id' => 321, 'name' => 'master-user.update', 'description' => 'Master user update'],
            ['id' => 322, 'name' => 'master-user.delete', 'description' => 'Master user delete'],
            ['id' => 323, 'name' => 'master-kontainer.view', 'description' => 'Master kontainer view'],
            ['id' => 324, 'name' => 'master-kontainer.create', 'description' => 'Master kontainer create'],
            ['id' => 325, 'name' => 'master-kontainer.update', 'description' => 'Master kontainer update'],
            ['id' => 326, 'name' => 'master-kontainer.delete', 'description' => 'Master kontainer delete'],
            ['id' => 327, 'name' => 'master-tujuan.view', 'description' => 'Master tujuan view'],
            ['id' => 328, 'name' => 'master-tujuan.create', 'description' => 'Master tujuan create'],
            ['id' => 329, 'name' => 'master-tujuan.update', 'description' => 'Master tujuan update'],
            ['id' => 330, 'name' => 'master-tujuan.delete', 'description' => 'Master tujuan delete'],
            ['id' => 331, 'name' => 'master-kegiatan.view', 'description' => 'Master kegiatan view'],
            ['id' => 332, 'name' => 'master-kegiatan.create', 'description' => 'Master kegiatan create'],
            ['id' => 333, 'name' => 'master-kegiatan.update', 'description' => 'Master kegiatan update'],
            ['id' => 334, 'name' => 'master-kegiatan.delete', 'description' => 'Master kegiatan delete'],
            ['id' => 335, 'name' => 'master-permission.view', 'description' => 'Master permission view'],
            ['id' => 336, 'name' => 'master-permission.create', 'description' => 'Master permission create'],
            ['id' => 337, 'name' => 'master-permission.update', 'description' => 'Master permission update'],
            ['id' => 338, 'name' => 'master-permission.delete', 'description' => 'Master permission delete'],
            ['id' => 339, 'name' => 'master-mobil.view', 'description' => 'Master mobil view'],
            ['id' => 340, 'name' => 'master-mobil.create', 'description' => 'Master mobil create'],
            ['id' => 341, 'name' => 'master-mobil.update', 'description' => 'Master mobil update'],
            ['id' => 342, 'name' => 'master-mobil.delete', 'description' => 'Master mobil delete'],
            ['id' => 343, 'name' => 'master-pricelist-sewa-kontainer.view', 'description' => 'Master pricelist sewa kontainer view'],
            ['id' => 344, 'name' => 'master-pricelist-sewa-kontainer.create', 'description' => 'Master pricelist sewa kontainer create'],
            ['id' => 345, 'name' => 'master-pricelist-sewa-kontainer.update', 'description' => 'Master pricelist sewa kontainer update'],
            ['id' => 346, 'name' => 'master-pricelist-sewa-kontainer.delete', 'description' => 'Master pricelist sewa kontainer delete'],
            ['id' => 347, 'name' => 'pranota.view', 'description' => 'Pranota view'],
            ['id' => 348, 'name' => 'pranota.create', 'description' => 'Pranota create'],
            ['id' => 349, 'name' => 'pranota.update', 'description' => 'Pranota update'],
            ['id' => 350, 'name' => 'pranota.delete', 'description' => 'Pranota delete'],
            ['id' => 351, 'name' => 'pranota.approve', 'description' => 'Pranota approve'],
            ['id' => 352, 'name' => 'pranota.print', 'description' => 'Pranota print'],
            ['id' => 353, 'name' => 'pranota.export', 'description' => 'Pranota export'],
            ['id' => 354, 'name' => 'pembayaran-pranota-kontainer.view', 'description' => 'Pembayaran pranota kontainer view'],
            ['id' => 355, 'name' => 'pembayaran-pranota-kontainer.create', 'description' => 'Pembayaran pranota kontainer create'],
            ['id' => 356, 'name' => 'pembayaran-pranota-kontainer.update', 'description' => 'Pembayaran pranota kontainer update'],
            ['id' => 357, 'name' => 'pembayaran-pranota-kontainer.delete', 'description' => 'Pembayaran pranota kontainer delete'],
            ['id' => 358, 'name' => 'pembayaran-pranota-kontainer.approve', 'description' => 'Pembayaran pranota kontainer approve'],
            ['id' => 359, 'name' => 'pembayaran-pranota-kontainer.print', 'description' => 'Pembayaran pranota kontainer print'],
            ['id' => 360, 'name' => 'pembayaran-pranota-kontainer.export', 'description' => 'Pembayaran pranota kontainer export'],
            ['id' => 361, 'name' => 'pranota-supir.view', 'description' => 'Pranota supir view'],
            ['id' => 362, 'name' => 'pranota-supir.update', 'description' => 'Pranota supir update'],
            ['id' => 363, 'name' => 'pranota-supir.delete', 'description' => 'Pranota supir delete'],
            ['id' => 364, 'name' => 'pranota-supir.approve', 'description' => 'Pranota supir approve'],
            ['id' => 365, 'name' => 'pranota-supir.export', 'description' => 'Pranota supir export'],
            ['id' => 366, 'name' => 'permohonan.view', 'description' => 'Permohonan view'],
            ['id' => 367, 'name' => 'permohonan.delete', 'description' => 'Permohonan delete'],
            ['id' => 368, 'name' => 'user-approval.view', 'description' => 'User approval view'],
            ['id' => 369, 'name' => 'user-approval.create', 'description' => 'User approval create'],
            ['id' => 370, 'name' => 'user-approval.update', 'description' => 'User approval update'],
            ['id' => 371, 'name' => 'user-approval.delete', 'description' => 'User approval delete'],
            ['id' => 372, 'name' => 'user-approval.print', 'description' => 'User approval print'],
            ['id' => 373, 'name' => 'user-approval.export', 'description' => 'User approval export'],
            ['id' => 374, 'name' => 'master-karyawan.print', 'description' => 'Master karyawan print'],
            ['id' => 375, 'name' => 'master-karyawan.export', 'description' => 'Master karyawan export'],
            ['id' => 376, 'name' => 'approval.view', 'description' => 'View approval tasks'],
            ['id' => 377, 'name' => 'approval.update', 'description' => 'Update approval tasks'],
            ['id' => 378, 'name' => 'approval.delete', 'description' => 'Delete approval tasks'],
            ['id' => 379, 'name' => 'approval.approve', 'description' => 'Approve tasks'],
            ['id' => 380, 'name' => 'approval.print', 'description' => 'Print approval reports'],
            ['id' => 381, 'name' => 'approval.export', 'description' => 'Export approval data'],
        ];

        $existingIds = DB::table('permissions')->pluck('id')->toArray();
        $newPermissions = [];

        foreach ($permissions as $permission) {
            if (!in_array($permission['id'], $existingIds)) {
                $newPermissions[] = array_merge($permission, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }

        if (!empty($newPermissions)) {
            DB::table('permissions')->insert($newPermissions);
            $this->command->info("Added " . count($newPermissions) . " new permissions from laptop database");
        } else {
            $this->command->info("All permissions from laptop database already exist");
        }

        $this->command->info('✅ Complete permissions sync completed!');
    }
}
