<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SyncUserPermissionSeeder extends Seeder
{
    /**
     * Sync user permissions from laptop database to server database.
     */
    public function run(): void
    {
        $this->command->info('🔐 Syncing user permissions from laptop database...');

        // Clear existing user_permissions and rebuild from laptop data
        DB::table('user_permissions')->truncate();

        // User permissions data from laptop database (aypsis_yang_benar.sql)
        $userPermissions = [
            // User 1 (admin) - ALL permissions
            ['user_id' => 1, 'permission_id' => 1],
            ['user_id' => 1, 'permission_id' => 2],
            ['user_id' => 1, 'permission_id' => 3],
            ['user_id' => 1, 'permission_id' => 4],
            ['user_id' => 1, 'permission_id' => 5],
            ['user_id' => 1, 'permission_id' => 6],
            ['user_id' => 1, 'permission_id' => 7],
            ['user_id' => 1, 'permission_id' => 8],
            ['user_id' => 1, 'permission_id' => 9],
            ['user_id' => 1, 'permission_id' => 10],
            ['user_id' => 1, 'permission_id' => 11],
            ['user_id' => 1, 'permission_id' => 12],
            ['user_id' => 1, 'permission_id' => 13],
            ['user_id' => 1, 'permission_id' => 14],
            ['user_id' => 1, 'permission_id' => 15],
            ['user_id' => 1, 'permission_id' => 16],
            ['user_id' => 1, 'permission_id' => 17],
            ['user_id' => 1, 'permission_id' => 18],
            ['user_id' => 1, 'permission_id' => 19],
            ['user_id' => 1, 'permission_id' => 20],
            ['user_id' => 1, 'permission_id' => 21],
            ['user_id' => 1, 'permission_id' => 22],
            ['user_id' => 1, 'permission_id' => 23],
            ['user_id' => 1, 'permission_id' => 24],
            ['user_id' => 1, 'permission_id' => 25],
            ['user_id' => 1, 'permission_id' => 26],
            ['user_id' => 1, 'permission_id' => 27],
            ['user_id' => 1, 'permission_id' => 28],
            ['user_id' => 1, 'permission_id' => 29],
            ['user_id' => 1, 'permission_id' => 30],
            ['user_id' => 1, 'permission_id' => 31],
            ['user_id' => 1, 'permission_id' => 32],
            ['user_id' => 1, 'permission_id' => 33],
            ['user_id' => 1, 'permission_id' => 34],
            ['user_id' => 1, 'permission_id' => 98],
            ['user_id' => 1, 'permission_id' => 99],
            ['user_id' => 1, 'permission_id' => 100],
            ['user_id' => 1, 'permission_id' => 101],
            ['user_id' => 1, 'permission_id' => 102],
            ['user_id' => 1, 'permission_id' => 103],
            ['user_id' => 1, 'permission_id' => 104],
            ['user_id' => 1, 'permission_id' => 105],
            ['user_id' => 1, 'permission_id' => 106],
            ['user_id' => 1, 'permission_id' => 107],
            ['user_id' => 1, 'permission_id' => 108],
            ['user_id' => 1, 'permission_id' => 109],
            ['user_id' => 1, 'permission_id' => 110],
            ['user_id' => 1, 'permission_id' => 111],
            ['user_id' => 1, 'permission_id' => 112],
            ['user_id' => 1, 'permission_id' => 113],
            ['user_id' => 1, 'permission_id' => 114],
            ['user_id' => 1, 'permission_id' => 115],
            ['user_id' => 1, 'permission_id' => 116],
            ['user_id' => 1, 'permission_id' => 117],
            ['user_id' => 1, 'permission_id' => 118],
            ['user_id' => 1, 'permission_id' => 119],
            ['user_id' => 1, 'permission_id' => 120],
            ['user_id' => 1, 'permission_id' => 121],
            ['user_id' => 1, 'permission_id' => 122],
            ['user_id' => 1, 'permission_id' => 123],
            ['user_id' => 1, 'permission_id' => 124],
            ['user_id' => 1, 'permission_id' => 125],
            ['user_id' => 1, 'permission_id' => 126],
            ['user_id' => 1, 'permission_id' => 127],
            ['user_id' => 1, 'permission_id' => 128],
            ['user_id' => 1, 'permission_id' => 129],
            ['user_id' => 1, 'permission_id' => 130],
            ['user_id' => 1, 'permission_id' => 131],
            ['user_id' => 1, 'permission_id' => 132],
            ['user_id' => 1, 'permission_id' => 133],
            ['user_id' => 1, 'permission_id' => 134],
            ['user_id' => 1, 'permission_id' => 135],
            ['user_id' => 1, 'permission_id' => 150],
            ['user_id' => 1, 'permission_id' => 179],
            ['user_id' => 1, 'permission_id' => 180],
            ['user_id' => 1, 'permission_id' => 181],
            ['user_id' => 1, 'permission_id' => 182],
            ['user_id' => 1, 'permission_id' => 183],
            ['user_id' => 1, 'permission_id' => 184],
            ['user_id' => 1, 'permission_id' => 185],
            ['user_id' => 1, 'permission_id' => 186],
            ['user_id' => 1, 'permission_id' => 187],
            ['user_id' => 1, 'permission_id' => 188],
            ['user_id' => 1, 'permission_id' => 189],
            ['user_id' => 1, 'permission_id' => 190],
            ['user_id' => 1, 'permission_id' => 191],
            ['user_id' => 1, 'permission_id' => 192],
            ['user_id' => 1, 'permission_id' => 193],
            ['user_id' => 1, 'permission_id' => 265],
            ['user_id' => 1, 'permission_id' => 266],
            ['user_id' => 1, 'permission_id' => 267],
            ['user_id' => 1, 'permission_id' => 268],
            ['user_id' => 1, 'permission_id' => 269],
            ['user_id' => 1, 'permission_id' => 270],
            ['user_id' => 1, 'permission_id' => 271],
            ['user_id' => 1, 'permission_id' => 272],
            ['user_id' => 1, 'permission_id' => 273],
            ['user_id' => 1, 'permission_id' => 274],
            ['user_id' => 1, 'permission_id' => 275],
            ['user_id' => 1, 'permission_id' => 276],
            ['user_id' => 1, 'permission_id' => 277],
            ['user_id' => 1, 'permission_id' => 278],
            ['user_id' => 1, 'permission_id' => 297],
            ['user_id' => 1, 'permission_id' => 298],
            ['user_id' => 1, 'permission_id' => 299],
            ['user_id' => 1, 'permission_id' => 300],
            ['user_id' => 1, 'permission_id' => 301],
            ['user_id' => 1, 'permission_id' => 302],
            ['user_id' => 1, 'permission_id' => 303],
            ['user_id' => 1, 'permission_id' => 304],
            ['user_id' => 1, 'permission_id' => 305],
            ['user_id' => 1, 'permission_id' => 306],
            ['user_id' => 1, 'permission_id' => 307],
            ['user_id' => 1, 'permission_id' => 308],
            ['user_id' => 1, 'permission_id' => 309],
            ['user_id' => 1, 'permission_id' => 310],
            ['user_id' => 1, 'permission_id' => 311],
            ['user_id' => 1, 'permission_id' => 312],
            ['user_id' => 1, 'permission_id' => 313],
            ['user_id' => 1, 'permission_id' => 314],
            ['user_id' => 1, 'permission_id' => 315],
            ['user_id' => 1, 'permission_id' => 316],
            ['user_id' => 1, 'permission_id' => 317],
            ['user_id' => 1, 'permission_id' => 318],
            ['user_id' => 1, 'permission_id' => 319],
            ['user_id' => 1, 'permission_id' => 320],
            ['user_id' => 1, 'permission_id' => 321],
            ['user_id' => 1, 'permission_id' => 322],
            ['user_id' => 1, 'permission_id' => 323],
            ['user_id' => 1, 'permission_id' => 324],
            ['user_id' => 1, 'permission_id' => 325],
            ['user_id' => 1, 'permission_id' => 326],
            ['user_id' => 1, 'permission_id' => 327],
            ['user_id' => 1, 'permission_id' => 328],
            ['user_id' => 1, 'permission_id' => 329],
            ['user_id' => 1, 'permission_id' => 330],
            ['user_id' => 1, 'permission_id' => 331],
            ['user_id' => 1, 'permission_id' => 332],
            ['user_id' => 1, 'permission_id' => 333],
            ['user_id' => 1, 'permission_id' => 334],
            ['user_id' => 1, 'permission_id' => 335],
            ['user_id' => 1, 'permission_id' => 336],
            ['user_id' => 1, 'permission_id' => 337],
            ['user_id' => 1, 'permission_id' => 338],
            ['user_id' => 1, 'permission_id' => 339],
            ['user_id' => 1, 'permission_id' => 340],
            ['user_id' => 1, 'permission_id' => 341],
            ['user_id' => 1, 'permission_id' => 342],
            ['user_id' => 1, 'permission_id' => 343],
            ['user_id' => 1, 'permission_id' => 344],
            ['user_id' => 1, 'permission_id' => 345],
            ['user_id' => 1, 'permission_id' => 346],
            ['user_id' => 1, 'permission_id' => 347],
            ['user_id' => 1, 'permission_id' => 348],
            ['user_id' => 1, 'permission_id' => 349],
            ['user_id' => 1, 'permission_id' => 350],
            ['user_id' => 1, 'permission_id' => 351],
            ['user_id' => 1, 'permission_id' => 352],
            ['user_id' => 1, 'permission_id' => 353],
            ['user_id' => 1, 'permission_id' => 354],
            ['user_id' => 1, 'permission_id' => 355],
            ['user_id' => 1, 'permission_id' => 356],
            ['user_id' => 1, 'permission_id' => 357],
            ['user_id' => 1, 'permission_id' => 358],
            ['user_id' => 1, 'permission_id' => 359],
            ['user_id' => 1, 'permission_id' => 360],
            ['user_id' => 1, 'permission_id' => 361],
            ['user_id' => 1, 'permission_id' => 362],
            ['user_id' => 1, 'permission_id' => 363],
            ['user_id' => 1, 'permission_id' => 364],
            ['user_id' => 1, 'permission_id' => 365],
            ['user_id' => 1, 'permission_id' => 366],
            ['user_id' => 1, 'permission_id' => 367],
            ['user_id' => 1, 'permission_id' => 368],
            ['user_id' => 1, 'permission_id' => 369],
            ['user_id' => 1, 'permission_id' => 370],
            ['user_id' => 1, 'permission_id' => 371],
            ['user_id' => 1, 'permission_id' => 372],
            ['user_id' => 1, 'permission_id' => 373],
            ['user_id' => 1, 'permission_id' => 374],
            ['user_id' => 1, 'permission_id' => 375],
            ['user_id' => 1, 'permission_id' => 376],
            ['user_id' => 1, 'permission_id' => 377],
            ['user_id' => 1, 'permission_id' => 378],
            ['user_id' => 1, 'permission_id' => 379],
            ['user_id' => 1, 'permission_id' => 380],
            ['user_id' => 1, 'permission_id' => 381],

            // User 2 (staff) - Limited permissions
            ['user_id' => 2, 'permission_id' => 5],
            ['user_id' => 2, 'permission_id' => 34],
            ['user_id' => 2, 'permission_id' => 100],
            ['user_id' => 2, 'permission_id' => 192],
            ['user_id' => 2, 'permission_id' => 379],

            // User 4 (kiky123) - Limited permissions
            ['user_id' => 4, 'permission_id' => 2],
            ['user_id' => 4, 'permission_id' => 315],
            ['user_id' => 4, 'permission_id' => 319],

            // User 5 - Specific permissions
            ['user_id' => 5, 'permission_id' => 319],

            // User 10 - Limited permissions
            ['user_id' => 10, 'permission_id' => 5],
            ['user_id' => 10, 'permission_id' => 34],
            ['user_id' => 10, 'permission_id' => 100],
            ['user_id' => 10, 'permission_id' => 192],
            ['user_id' => 10, 'permission_id' => 193],
            ['user_id' => 10, 'permission_id' => 272],
            ['user_id' => 10, 'permission_id' => 273],
            ['user_id' => 10, 'permission_id' => 304],
            ['user_id' => 10, 'permission_id' => 376],
            ['user_id' => 10, 'permission_id' => 379],

            // User 15 - Limited permissions
            ['user_id' => 15, 'permission_id' => 1],
            ['user_id' => 15, 'permission_id' => 315],
        ];

        // Insert all user permissions
        $chunks = array_chunk($userPermissions, 100);
        foreach ($chunks as $chunk) {
            DB::table('user_permissions')->insert($chunk);
        }

        $this->command->info("Synced " . count($userPermissions) . " user permissions from laptop database");

        $this->command->info('✅ User permissions sync completed!');
    }
}
