#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

define('LARAVEL_START', microtime(true));

// Check If The Application Is Under Maintenance
if (file_exists(__DIR__.'/storage/framework/maintenance.php')) {
    require __DIR__.'/storage/framework/maintenance.php';
}

// Register The Composer Autoloader
require __DIR__.'/vendor/autoload.php';

// Bootstrap The Application And Handle The Command
(require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
