#!/bin/bash

# ====================================
# PERINTAH DEPLOY KE SERVER PRODUCTION
# ====================================

echo "🚀 DEPLOYMENT COMMANDS FOR PRODUCTION SERVER"
echo "============================================="
echo ""

echo "📋 STEP 1: Connect to Server"
echo "============================="
echo "ssh username@your-server-ip"
echo "# atau"
echo "ssh username@your-domain.com"
echo ""

echo "📋 STEP 2: Navigate to Project Directory"
echo "========================================"
echo "cd /path/to/your/aypsis/project"
echo "# contoh:"
echo "cd /var/www/html/aypsis"
echo "# atau"
echo "cd /home/username/aypsis"
echo ""

echo "📋 STEP 3: Pull Latest Changes"
echo "=============================="
echo "git pull origin main"
echo ""

echo "📋 STEP 4: Update Dependencies (if needed)"
echo "=========================================="
echo "composer install --no-dev --optimize-autoloader"
echo ""

echo "📋 STEP 5: Clear Laravel Cache"
echo "=============================="
echo "php artisan config:clear"
echo "php artisan cache:clear"
echo "php artisan view:clear"
echo "php artisan route:clear"
echo ""

echo "📋 STEP 6: Optimize for Production"
echo "=================================="
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo ""

echo "📋 STEP 7: Run Migrations (if any)"
echo "=================================="
echo "php artisan migrate --force"
echo ""

echo "📋 STEP 8: Set Permissions (if needed)"
echo "======================================"
echo "sudo chown -R www-data:www-data ."
echo "sudo chmod -R 755 ."
echo "sudo chmod -R 775 storage"
echo "sudo chmod -R 775 bootstrap/cache"
echo ""

echo "🔥 COMPLETE DEPLOYMENT SCRIPT:"
echo "==============================="
echo "ssh username@your-server && \\"
echo "cd /var/www/html/aypsis && \\"
echo "git pull origin main && \\"
echo "composer install --no-dev --optimize-autoloader && \\"
echo "php artisan config:clear && \\"
echo "php artisan cache:clear && \\"
echo "php artisan view:clear && \\"
echo "php artisan route:clear && \\"
echo "php artisan config:cache && \\"
echo "php artisan route:cache && \\"
echo "php artisan view:cache && \\"
echo "php artisan migrate --force && \\"
echo "sudo chown -R www-data:www-data . && \\"
echo "sudo chmod -R 755 . && \\"
echo "sudo chmod -R 775 storage && \\"
echo "sudo chmod -R 775 bootstrap/cache"
echo ""

echo "💡 TIPS:"
echo "========"
echo "1. Backup database sebelum deploy: mysqldump -u user -p database > backup.sql"
echo "2. Test di staging server dulu sebelum production"
echo "3. Monitor logs setelah deploy: tail -f storage/logs/laravel.log"
echo "4. Check website functionality setelah deploy"
echo ""

echo "🚨 ROLLBACK (jika ada masalah):"
echo "==============================="
echo "git log --oneline -5  # lihat commit history"
echo "git reset --hard COMMIT_HASH  # rollback ke commit sebelumnya"
echo "# atau"
echo "git revert HEAD  # buat commit baru yang undo changes"
