#!/bin/bash

# ====================================
# PERINTAH MIGRATION UNTUK SERVER
# ====================================

echo "🗄️  DATABASE MIGRATION COMMANDS FOR SERVER"
echo "==========================================="
echo ""

echo "📋 STEP 1: Connect to Server"
echo "============================="
echo "ssh username@your-server-ip"
echo ""

echo "📋 STEP 2: Navigate to Project Directory"
echo "========================================"
echo "cd /var/www/html/aypsis"
echo "# atau sesuai path project Anda"
echo ""

echo "📋 STEP 3: Check Migration Status"
echo "================================="
echo "php artisan migrate:status"
echo "# Untuk melihat migration mana yang sudah/belum dijalankan"
echo ""

echo "📋 STEP 4: Backup Database (PENTING!)"
echo "====================================="
echo "mysqldump -u username -p database_name > backup_before_migration_\$(date +%Y%m%d_%H%M%S).sql"
echo "# Ganti 'username' dan 'database_name' sesuai dengan setup Anda"
echo ""

echo "📋 STEP 5: Run Migration"
echo "========================"
echo "php artisan migrate"
echo "# atau untuk production:"
echo "php artisan migrate --force"
echo ""

echo "📋 STEP 6: Verify Migration Success"
echo "==================================="
echo "php artisan migrate:status"
echo "# Pastikan semua migration berstatus 'Y'"
echo ""

echo "🔥 COMPLETE MIGRATION COMMAND (One-liner):"
echo "==========================================="
echo "ssh username@server && cd /var/www/html/aypsis && php artisan migrate:status && php artisan migrate --force && php artisan migrate:status"
echo ""

echo "🛠️  TROUBLESHOOTING COMMANDS:"
echo "============================="
echo ""
echo "1. Rollback last migration (jika ada error):"
echo "   php artisan migrate:rollback"
echo ""
echo "2. Rollback specific batch:"
echo "   php artisan migrate:rollback --batch=3"
echo ""
echo "3. Reset all migrations (HATI-HATI!):"
echo "   php artisan migrate:reset"
echo ""
echo "4. Fresh migration (DROP ALL TABLES!):"
echo "   php artisan migrate:fresh"
echo ""
echo "5. Check database connection:"
echo "   php artisan tinker"
echo "   >>> DB::connection()->getPdo();"
echo "   >>> exit"
echo ""

echo "📊 FIELD BARU YANG MUNGKIN PERLU MIGRATION:"
echo "==========================================="
echo "Berdasarkan analisis kode, field baru yang terdeteksi:"
echo "- tanggal_masuk_sebelumnya (sudah ada di migration)"
echo "- tanggal_berhenti_sebelumnya (sudah ada di migration)"
echo "- catatan (perlu ditambahkan)"
echo "- bank_cabang (perlu ditambahkan)"
echo "- no_ketenagakerjaan (perlu ditambahkan)"
echo ""

echo "🆕 GENERATE MIGRATION UNTUK FIELD BARU:"
echo "======================================="
echo "php artisan make:migration add_missing_fields_to_karyawans_table --table=karyawans"
echo ""

echo "💡 TIPS MIGRATION DI PRODUCTION:"
echo "================================"
echo "1. Selalu backup database sebelum migration"
echo "2. Test migration di staging server dulu"
echo "3. Jalankan migration saat traffic rendah"
echo "4. Monitor aplikasi setelah migration"
echo "5. Siapkan rollback plan"
echo ""

echo "🚨 EMERGENCY ROLLBACK:"
echo "======================"
echo "Jika ada masalah setelah migration:"
echo "1. php artisan migrate:rollback"
echo "2. Atau restore dari backup:"
echo "   mysql -u username -p database_name < backup_file.sql"
