#!/bin/bash

# Solusi untuk mengatasi git pull error pada server
# Jalankan command ini pada server: /var/www/aypsis

echo "=== SOLUSI 1: STASH PERUBAHAN LOKAL ==="
echo "1. Simpan perubahan lokal sementara:"
echo "   git stash push -m 'Local changes before pull'"
echo ""
echo "2. Pull perubahan terbaru:"
echo "   git pull origin main"
echo ""
echo "3. (Opsional) Restore perubahan lokal jika dibutuhkan:"
echo "   git stash pop"
echo ""

echo "=== SOLUSI 2: FORCE OVERWRITE (HATI-HATI) ==="
echo "Jika perubahan lokal tidak penting:"
echo "1. Reset file yang konflik:"
echo "   git checkout -- fix_foreign_key_server.sh"
echo ""
echo "2. Pull perubahan:"
echo "   git pull origin main"
echo ""

echo "=== SOLUSI 3: BACKUP & RESET ==="
echo "1. Backup file yang konflik:"
echo "   cp fix_foreign_key_server.sh fix_foreign_key_server.sh.backup"
echo ""
echo "2. Reset file:"
echo "   git checkout -- fix_foreign_key_server.sh"
echo ""
echo "3. Pull perubahan:"
echo "   git pull origin main"
echo ""
echo "4. Compare jika perlu:"
echo "   diff fix_foreign_key_server.sh fix_foreign_key_server.sh.backup"
echo ""

echo "=== COMMAND LENGKAP UNTUK SERVER ==="
echo "# Jalankan salah satu blok command berikut di server:"
echo ""
echo "# OPSI A - Stash (Aman, menyimpan perubahan lokal)"
echo "cd /var/www/aypsis"
echo "git stash push -m 'Local server changes before pull'"
echo "git pull origin main"
echo ""
echo "# OPSI B - Force overwrite (Menghapus perubahan lokal)"
echo "cd /var/www/aypsis"
echo "git checkout -- fix_foreign_key_server.sh"
echo "git pull origin main"
echo ""
echo "# OPSI C - Backup first (Aman dengan backup)"
echo "cd /var/www/aypsis"
echo "cp fix_foreign_key_server.sh fix_foreign_key_server.sh.backup"
echo "git checkout -- fix_foreign_key_server.sh"
echo "git pull origin main"
