@extends('layouts.print')

@section('content')
<div style="padding:12px;">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;">
        <div>
            <h1 style="font-size:18px;margin:0;">Daftar Karyawan</h1>
            <div style="font-size:12px;color:#555;">Total: {{ $karyawans->count() }}</div>
        </div>
        <div style="text-align:right;font-size:12px;color:#444;">Dicetak: {{ now()->format('Y-m-d H:i') }}</div>
    </div>

    @php use Carbon\Carbon; @endphp
    <table style="width:100%;border-collapse:collapse;font-size:12px;">
        <thead>
            <tr>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">NIK</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Nama Lengkap</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Nama Panggilan</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Divisi</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Pekerjaan</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">No. HP</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Email</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Tanggal Masuk</th>
                <th style="border:1px solid #ddd;padding:6px;background:#f3f4f6;text-align:left;">Tanggal Berhenti</th>
            </tr>
        </thead>
        <tbody>
            @forelse($karyawans as $k)
                <tr>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->nik ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->nama_lengkap ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->nama_panggilan ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->divisi ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->pekerjaan ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->no_hp ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->email ?? '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->tanggal_masuk ? Carbon::parse($k->tanggal_masuk)->format('Y-m-d') : '-' }}</td>
                    <td style="border:1px solid #ddd;padding:6px;">{{ $k->tanggal_berhenti ? Carbon::parse($k->tanggal_berhenti)->format('Y-m-d') : '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="border:1px solid #ddd;padding:8px;text-align:center;color:#666;">Belum ada data karyawan.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div style="margin-top:12px;font-size:11px;color:#666;">Generated by {{ config('app.name') }}</div>
</div>
@endsection
